services:
  backend:
    build: 
      context: ./backend/
    container_name: lister_backend 
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    # command: "sh /app/scripts/startapp.sh"
    command: "python app/main.py"
    # env_file:
    #   - ./backend/.env
    volumes:
      - ./backend:/app/
    restart: on-failure

  bot:
    build:
      context: ./tg_bot/ 
    container_name: lister_bot
    command: "python src/main.py"
    volumes:
      - ./tg_bot/:/app/
    # env_file:
    #   - ./tg_bot/.env 
    restart: on-failure

  mongo:
    image: mongo
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME} 
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    restart: on-failure
  
  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: hackme
  #     ME_CONFIG_MONGODB_URL: mongodb://root:hackme@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
