services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ~/docker_volumes/postgres/lister_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend/
    container_name: lister_backend 
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    env-file:
      - ./.env
    docker_volumes:
      - ./backend/:/app/
    restart: on-failure

  # bot:
  #   build:
  #     context: ./tg_bot/ 
  #   container_name: lister_bot
  #   restart: on-failure
